"use client";
import localFont from "next/font/local";
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/
import Header from "./header"
import Footer from "./footer";
import { Children } from "react";
import { SessionProvider } from "next-auth/react";


import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
//import Footer from "./footer" 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        
        <SessionProvider>
          <Header/>
          <main className="flex-grow">
          {children}
          <Footer/>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}

